### PR TITLE
Bump node to 8.10.0-pre

### LINKED ISSUE #385: `DecoderFailure (ChainSync...` when using with Cardano Node 8.10.0-pre
### What Git revision / release tag are you using?

6.2.0

### Do you use any client SDK? If yes, which one?

TypeScript

### Describe what the problem is?

Is there an Ogmios upgrade for CardanoNode 8.10.0-pre is in the pipeline.

I am still trying to figure out exactly which calls are causing this, but I am seeing this error in the Ogmios log.
```
{"severity":"Error","timestamp":"2024-04-19T14:15:04.344657718Z","thread":"22233","message":{"WebSocket":{"exception":"DecoderFailure (ChainSync (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra Stand
ardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *))))))))
) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra St
andardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))))) ServerAgency TokNext TokCanAwait) (DeserialiseFailure 1226 \"expected list len or indef\")","tag":"WebSocketUnknownException"}},"version
":"v6.2.0 (088501eb)"}
```
There's also a `Websocket unexpectedly closed with code 1006` error in the client code connecting to Ogmios.
Right before this, I printed the latest transaction cbor, but I am unsure whether it is related:
`84a300d901028182582039b2a411cf7e8ce53e8ea60624ac08e1ebf79b3748bd0ededb429955a9f12b9101018283581d7067f33146617a5e61936081db3b2117cbf59bd2123748f58ac96786561a05f5e10058205e9d8bac576e8604e7c3526025bc146f5fa178173e3a5592d122687bd785b52082581d60137e06438b62e62f6ac91f7ecd5c10f3e4893e3fe6082693870d4f8f1b000d1423a88d30d3021a00029ee5a100d90102818258203c15543ca4a592745513500ed23bd6857dc3ffb4f6ac7e2350673e0c1ab360705840bf935f1e55c459f75c8b79081fbd6dc0aacda59b04f30a9e`

Network: a conway-era private network.

### What should be the expected behavior?

Should not disconnect websocket and throw error.

### If applicable, what are the logs from the server around the occurence of the problem?

```
{"severity":"Info","timestamp":"2024-04-19T14:14:54.615316603Z","thread":"19774","message":{"WebSocket":{"contents":{"atSlot":12339,"ns":198237099211040,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:14:54.615585322Z","thread":"624","message":{"WebSocket":{"contents":{"atSlot":12339,"ns":198237099498566,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:14:54.616053535Z","thread":"624","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"467µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:14:54.616252307Z","thread":"19774","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"952µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                  
{"severity":"Info","timestamp":"2024-04-19T14:14:58.433921803Z","thread":"624","message":{"WebSocket":{"contents":{"atSlot":12358,"ns":198240917830008,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}  
{"severity":"Info","timestamp":"2024-04-19T14:14:58.434535993Z","thread":"624","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"616µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:14:58.434625859Z","thread":"19774","message":{"WebSocket":{"contents":{"atSlot":12358,"ns":198240918538902,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:14:58.434847291Z","thread":"19774","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"221µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                 
{"severity":"Info","timestamp":"2024-04-19T14:14:58.435162573Z","thread":"17","message":{"Health":{"tag":"HealthTick","status":{"startTime":"2024-04-19T13:43:50.049824459Z","lastKnownTip":{"slot":12357,"id":"01b8886cf3942141e6d6eed66296d997c16cc91a8d8521e234c9b6d93c7d0041","height":1247},"lastTipUpdate":"2024-
04-19T14:14:58.435040171Z","networkSynchronization":1.00000,"currentEra":"conway","metrics":{"activeConnections":2,"runtimeStats":{"cpuTime":33160529396,"currentHeapSize":1619,"gcCpuTime":21031692107,"maxHeapSize":1960},"sessionDurations":{"max":0,"mean":1765.2765460910152,"min":0},"totalConnections":859,"tota
lMessages":4747,"totalUnrouted":0},"connectionStatus":"connected","currentEpoch":12,"slotInEpoch":357,"version":"v6.2.0 (088501eb)","network":"unknown (888)"}}},"version":"v6.2.0 (088501eb)"}                                                 
{"severity":"Info","timestamp":"2024-04-19T14:14:59.320152419Z","thread":"22207","message":{"WebSocket":{"tag":"WebSocketConnectionAccepted","userAgent":"User-Agent unknown"}},"version":"v6.2.0 (088501eb)"}                                                      
{"severity":"Info","timestamp":"2024-04-19T14:14:59.320591686Z","thread":"22211","message":{"WebSocket":{"contents":{"agency":"ClientAgency TokPropose","event":"send","tag":"ProposeVersions","versions":["NodeToClientV_15","NodeToClientV_16"]},"tag":"WebSocketClient"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:14:59.320689698Z","thread":"22212","message":{"WebSocket":{"contents":{"agency":"ClientAgency TokPropose","event":"send","tag":"ProposeVersions","versions":["NodeToClientV_15","NodeToClientV_16"]},"tag":"WebSocketClient"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:14:59.321263387Z","thread":"22211","message":{"WebSocket":{"contents":{"agency":"ServerAgency TokConfirm","event":"receive","tag":"AcceptVersion","version":"\"NodeToClientV_16\""},"tag":"WebSocketClient"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:14:59.321530746Z","thread":"22212","message":{"WebSocket":{"contents":{"agency":"ServerAgency TokConfirm","event":"receive","tag":"AcceptVersion","version":"\"NodeToClientV_16\""},"tag":"WebSocketClient"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:14:59.322613823Z","thread":"22229","message":{"WebSocket":{"contents":{"atSlot":12358,"ns":198241806524328,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:14:59.323030526Z","thread":"22229","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"417µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Error","timestamp":"2024-04-19T14:14:59.325568813Z","thread":"22207","message":{"WebSocket":{"exception":"DecoderFailure (ChainSync (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra Stand
ardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *))))))))
) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra St
andardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))))) ServerAgency TokNext TokCanAwait) (DeserialiseFailure 1226 \"expected list len or indef\")","tag":"WebSocketUnknownException"}},"version
":"v6.2.0 (088501eb)"}                                                                                                                                                                                                                                                                                                 
{"severity":"Info","timestamp":"2024-04-19T14:14:59.325678099Z","thread":"22207","message":{"WebSocket":{"tag":"WebSocketConnectionEnded","userAgent":"User-Agent unknown"}},"version":"v6.2.0 (088501eb)"}                                                         
{"severity":"Info","timestamp":"2024-04-19T14:15:00.227525376Z","thread":"624","message":{"WebSocket":{"contents":{"atSlot":12367,"ns":198242711431796,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:15:00.227997916Z","thread":"19774","message":{"WebSocket":{"contents":{"atSlot":12367,"ns":198242711906071,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:15:00.228547953Z","thread":"624","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"1024µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"} 
{"severity":"Info","timestamp":"2024-04-19T14:15:00.228617407Z","thread":"19774","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"562µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                                                                       
{"severity":"Info","timestamp":"2024-04-19T14:15:00.412799568Z","thread":"624","message":{"WebSocket":{"contents":{"atSlot":12368,"ns":198242896709922,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                                                     
{"severity":"Info","timestamp":"2024-04-19T14:15:00.412914986Z","thread":"19774","message":{"WebSocket":{"contents":{"atSlot":12368,"ns":198242896830313,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:15:00.413242617Z","thread":"19774","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"322µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                    
{"severity":"Info","timestamp":"2024-04-19T14:15:00.413285224Z","thread":"624","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"476µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                    
{"severity":"Info","timestamp":"2024-04-19T14:15:02.615204165Z","thread":"624","message":{"WebSocket":{"contents":{"atSlot":12379,"ns":198245099109821,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:15:02.615383974Z","thread":"19774","message":{"WebSocket":{"contents":{"atSlot":12379,"ns":198245099290391,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:15:02.616121922Z","thread":"624","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"918µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                    
{"severity":"Info","timestamp":"2024-04-19T14:15:02.616419028Z","thread":"19774","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"1032µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                   
{"severity":"Info","timestamp":"2024-04-19T14:15:03.613157494Z","thread":"624","message":{"WebSocket":{"contents":{"atSlot":12384,"ns":198246097060295,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:15:03.61331121Z","thread":"19774","message":{"WebSocket":{"contents":{"atSlot":12384,"ns":198246097077928,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:15:03.613844817Z","thread":"624","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"690µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                      
{"severity":"Info","timestamp":"2024-04-19T14:15:03.614127498Z","thread":"19774","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"955µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                  
{"severity":"Info","timestamp":"2024-04-19T14:15:04.339165334Z","thread":"22233","message":{"WebSocket":{"tag":"WebSocketConnectionAccepted","userAgent":"User-Agent unknown"}},"version":"v6.2.0 (088501eb)"}                                   
{"severity":"Info","timestamp":"2024-04-19T14:15:04.339629416Z","thread":"22237","message":{"WebSocket":{"contents":{"agency":"ClientAgency TokPropose","event":"send","tag":"ProposeVersions","versions":["NodeToClientV_15","NodeToClientV_16"]},"tag":"WebSocketClient"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:15:04.339722337Z","thread":"22238","message":{"WebSocket":{"contents":{"agency":"ClientAgency TokPropose","event":"send","tag":"ProposeVersions","versions":["NodeToClientV_15","NodeToClientV_16"]},"tag":"WebSocketClient"}},"version":"v6.2.0 (088501eb)"}            
{"severity":"Info","timestamp":"2024-04-19T14:15:04.340136849Z","thread":"22237","message":{"WebSocket":{"contents":{"agency":"ServerAgency TokConfirm","event":"receive","tag":"AcceptVersion","version":"\"NodeToClientV_16\""},"tag":"WebSocketClient"}},"version":"v6.2.0 (088501eb)"}                             
{"severity":"Info","timestamp":"2024-04-19T14:15:04.34022922Z","thread":"22238","message":{"WebSocket":{"contents":{"agency":"ServerAgency TokConfirm","event":"receive","tag":"AcceptVersion","version":"\"NodeToClientV_16\""},"tag":"WebSocketClient"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:15:04.341428297Z","thread":"22256","message":{"WebSocket":{"contents":{"atSlot":12384,"ns":198246825341102,"tag":"TxSubmissionLocalMempoolNewSnapshot"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}
{"severity":"Info","timestamp":"2024-04-19T14:15:04.342048706Z","thread":"22256","message":{"WebSocket":{"contents":{"tag":"TxSubmissionLocalMempoolSynchronized","took":"620µs"},"tag":"WebSocketTxSubmission"}},"version":"v6.2.0 (088501eb)"}                    
{"severity":"Error","timestamp":"2024-04-19T14:15:04.344657718Z","thread":"22233","message":{"WebSocket":{"exception":"DecoderFailure (ChainSync (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra Stand
ardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *))))))))
) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (TPraos StandardCrypto) (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AllegraEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (MaryEra StandardCrypto)) (': * (ShelleyBlock (TPraos StandardCrypto) (AlonzoEra St
andardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (BabbageEra StandardCrypto)) (': * (ShelleyBlock (Praos StandardCrypto) (ConwayEra StandardCrypto)) ('[] *)))))))))) ServerAgency TokNext TokCanAwait) (DeserialiseFailure 1226 \"expected list len or indef\")","tag":"WebSocketUnknownException"}},"version
":"v6.2.0 (088501eb)"}                                                                                                                                                                                                                                                                                                 
{"severity":"Info","timestamp":"2024-04-19T14:15:04.344765232Z","thread":"22233","message":{"WebSocket":{"tag":"WebSocketConnectionEnded","userAgent":"User-Agent unknown"}},"version":"v6.2.0 (088501eb)"}
```

### PR DESCRIPTION
**Pull request by klarkc**
- Bump mainnet node to 8.9.2 (because cardano-configuration changed)
- Bump sanchonet node to 8.10.0-pre

Fix #385

### CODE REVIEW

**Comment by KtorZ** [comment]
(note: I am working on bumping to 8.10.1-pre at the moment)

**Comment by klarkc** [comment]
@KtorZ I've pushed my recent local changes. Please feel free to use this branch, but it's not building yet.

**Comment by KtorZ** [comment]
I have a branch building. I've been re-using some of your stuff, changed some others. So I'll put you as co-author :)

**Comment by klarkc** [comment]
Superseded by 7dc8742caad909a9d67ca502a239a1ab3b6029ef

**Pull request closed without merging**
