### PR TITLE
Integrate cardano-node == 8.8.0

### PR DESCRIPTION
**Pull request by KtorZ**

### CODE REVIEW

**Comment by mirceahasegan** [comment]
Hello. Is there a rough estimate for when this will be merged? Thank you!

**Comment by KtorZ** [comment]
Man you gotta chill a bit with the constant ping on getting Ogmios upgrades☺️, this is how you drive open source maintainers crazy. 

Ogmios is a free software provided as-is. It is usually updated within 1-3 weeks following node updates and there will be no more precise timelines that this ever given.

**Comment by mirceahasegan** [comment]
Much appreciated @KtorZ . Sorry for the eager beaver routine 🦫 . 1-3 weeks is more than accurate.
Thanks for all your hard work! 🌟

**Comment by KtorZ** [comment]
Merged manually in 8771c46089c75521a9fae1daf857336b3e6e09e1

**Pull request closed without merging**
