### PR TITLE
Chore/bump cardano node to 1.35.3 and cardano-configurations to latest

### PR DESCRIPTION
**Pull request by rhyslbw**

### CODE REVIEW

**Comment by KtorZ** [comment]
Hmmm. Looks like the Vasil devnet was restarted in August. Needs to fix the options spec.

**Comment by rhyslbw** [comment]
I've added the new testnets in 5f343ee4a34467c091cb4ba04777019f62da7703. For information relating to these, see https://book.world.dev.cardano.org/environments.html

**Comment by rhyslbw** [comment]
We'll also need to drop _testnet_ and ensure TS tests are all passing on _preprod_. I'm out of time tonight, but can sort it tomorrow during my daylight hours.

**Comment by KtorZ** [comment]
> since cardano-node@1.35.3 is no longer able to sync to the tip 

:|

**Comment by rhyslbw** [comment]
I've found a bug in the TS client that needs addressing. `EvaluationFailure[ScriptFailures]` is an [object](https://github.com/CardanoSolutions/ogmios/blob/e2a6ff63e06be3b16065c82a9c0e3be7d51dfca1/docs/static/ogmios.wsp.json#L2732), but it's [expected to be an array](https://github.com/CardanoSolutions/ogmios/blob/e2a6ff63e06be3b16065c82a9c0e3be7d51dfca1/clients/TypeScript/packages/client/src/TxSubmission/evaluateTx.ts#L63), with no `else` clause to handle the exception. Curiously there's been no changes from the original implementation, so it's surprising to only be caught now :thinking:

**Comment by KtorZ** [comment]
Interesting. You only hit evaluation failures though when you explicitly evaluate execution units, not when submitting. So if you've not been using that feature before, you'd have not noticed.

**Pull request merged**
