### PR TITLE
Add upgrade unsafeFromRight reporting workaround

### PR DESCRIPTION
**Pull request by klarkc**
I'm encountering an upgrade (https://github.com/CardanoSolutions/ogmios/issues/363#issuecomment-1953067395) decode error again (but for different reasons), and just like before, it's not being reported. Therefore, I'm proposing this change until we establish a better method for reporting decode errors in the upgrade function.

Related #363

### CODE REVIEW

**Comment by KtorZ** [comment]
@klarkc not a big fan of the change 😬 ... this kind of temporary fix ends up being more permanent than we usually want initially. 

So I am more for biting the bullet and getting those async exception handled properly. It might just be a matter of linking the async thread with the parent as this should crash the entire connection. 

Do you have an easy reproduction step here by the way? I can always just shove an artificial `undefined` here and there, but I am genuinely curious about what's causing this now?

**Comment by klarkc** [comment]
@KtorZ It happened with ogmios [`v6.1.0`](https://github.com/CardanoSolutions/ogmios/releases/tag/v6.1.0) and cardano-node `8.8.0-pre`. Like before, it is happening with any script version (PlutusV1, V2 and V3). Removing the cardano-node volume did not fixed the issue this time. The error (not being reported) is the same:

> "DecoderErrorDeserialiseFailure \"witness\" (DeserialiseFailure 38 \"expected bytes\")"

I don't have a reproduction repo now as I'm already moving to `v6.2.0` with cardano-node `8.9.1`, but if this version also fails I'll try to provide a repo :+1:.

**Comment by KtorZ** [comment]
Hey, @klarkc I've been trying to reproduce by forcing the an exception at upgrade's call site but the server behaves "as expected":

```
{
  code: -32603,
  message: '"foo"\n' +
    'CallStack (from HasCallStack):\n' +
    '  error, called at src/Relude/Debug.hs:296:11 in rld-1.2.1.0-1d38cbc5:Relude.Debug\n' +
    '  error, called at src/Ogmios/App/Protocol/TxSubmission.hs:296:39 in ogmios-0-inplace:Ogmios.App.Protocol.TxSubmission\n' +
    '  unsafeFromRight, called at src/Ogmios/App/Protocol/TxSubmission.hs:293:28 in ogmios-0-inplace:Ogmios.App.Protocol.TxSubmission'
}
```

Maybe it's the cardano-transaction-lib that isn't handling server errors properly?

**Comment by KtorZ** [comment]
That's a good point. I didn;'t check the server logs (🤦) because I got a response from the client side already.

**Pull request closed without merging**
